import{test,expect}from'@playwright/test';
import{randomBytes}from'node:crypto';
import{createClient}from'@supabase/supabase-js';
const url=process.env.VITE_SUPABASE_URL;if(!['localhost','127.0.0.1'].includes(new URL(url).hostname))throw Error('Local DB only');
const service=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const ok=async q=>{const{data,error}=await q;if(error)throw Error(error.message);return data;};
let copy,legal;
test.beforeAll(async()=>{copy=await ok(service.from('site_content').select('*').eq('section','copy').maybeSingle());legal=await ok(service.from('site_content').select('*').eq('section','legal').maybeSingle());});
test.afterAll(async()=>{for(const [section,row]of [['copy',copy],['legal',legal]]){if(row)await service.from('site_content').upsert(row);else await service.from('site_content').delete().eq('section',section);}});
async function login(page){await page.goto('/admin/login');await page.getByLabel('E-mail',{exact:false}).fill(process.env.DEMO_ADMIN_EMAIL);await page.getByLabel('Senha',{exact:false}).fill(process.env.DEMO_ADMIN_PASSWORD);await page.getByRole('button',{name:'Entrar',exact:false}).click();await expect(page.locator('.metrics')).toBeVisible();await page.goto('/admin/site');await expect(page.locator('#section')).toBeVisible();}
async function save(page){const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/rest/v1/site_content');const button=page.getByRole('button',{name:'Salvar e publicar seção'});await button.click();expect((await response).ok()).toBe(true);await expect(button).toBeEnabled();await expect(page.locator('.toast').last()).toContainText('Seção publicada');}
test('Admin publishes header/footer, changes menus, preserves legal copy and renders safely on mobile',async({page,browser})=>{
 await login(page);await page.locator('#section').selectOption('header');await page.getByLabel('Nome exibido na marca',{exact:true}).fill('CLÍNICA TESTE');await page.getByLabel('Texto do botão de agendamento').fill('Escolher meu horário');await page.getByLabel('Texto para entrar na conta').fill('Acessar perfil');await page.getByLabel('Texto acessível para abrir o menu').fill('Abrir navegação');await page.getByLabel('Texto acessível para fechar o menu').fill('Fechar navegação');await save(page);
 await page.locator('#section').selectOption('header_links');await page.getByLabel('Texto do link',{exact:true}).first().fill('Conheça a clínica');await page.getByLabel('Destino do link',{exact:true}).first().fill('#sobre');await page.locator('[data-up="1"]').click();await page.locator('[data-remove]').last().click();await page.getByRole('button',{name:'+ Adicionar item'}).click();await page.getByLabel('Texto do link',{exact:true}).last().fill('Instagram oficial');await page.getByLabel('Destino do link',{exact:true}).last().fill('https://instagram.com/clinicateste');await page.getByLabel('Abrir em nova aba').last().selectOption('true');await save(page);
 await page.locator('#section').selectOption('footer');await page.getByLabel('Nome exibido na marca',{exact:true}).fill('MARCA DO RODAPÉ');await page.getByLabel('Descrição abaixo da marca').fill('Cuidado com atenção.');await page.getByLabel('Título da coluna de navegação').fill('Explore');await page.getByLabel('Título da coluna de contatos').fill('Fale conosco');await page.getByLabel('Usar contatos das Configurações da clínica').selectOption('false');await page.getByLabel('Endereço próprio do rodapé').fill('Rua de Demonstração, 123');await page.getByLabel('Telefone próprio do rodapé').fill('+55 11 99999-0000');await page.getByLabel('E-mail próprio do rodapé').fill('contato@example.invalid');await page.getByLabel('Horários próprios do rodapé').fill('Segunda a sexta\n09h às 18h');await page.getByLabel('Exibir telefone').selectOption('true');await page.getByLabel('Exibir horários').selectOption('true');await page.getByLabel('Texto de direitos autorais',{exact:false}).fill('© {ano} {clinica} — feito com cuidado');await page.getByLabel('Texto do botão de privacidade').fill('Nossa privacidade');await page.getByLabel('Texto do botão de termos').fill('Regras de uso');await page.getByLabel('Texto adicional do rodapé').fill('<img src=x onerror=alert(1)> texto simples');await page.getByLabel('Exibir nota de demonstração').selectOption('false');await save(page);
 await page.locator('#section').selectOption('footer_links');await page.getByLabel('Texto do link',{exact:true}).first().fill('Nossos serviços');await page.getByLabel('Destino do link',{exact:true}).first().fill('#procedimentos');await save(page);
 await page.locator('#section').selectOption('footer_contacts');await page.getByLabel('Texto do link',{exact:true}).first().fill('Enviar e-mail');await page.getByLabel('Destino do link',{exact:true}).first().fill('mailto:contato@example.invalid');await save(page);
 await page.locator('#section').selectOption('legal');await page.getByLabel('Política de privacidade').fill('Política publicada pela clínica: conteúdo de teste.');await save(page);
 await page.locator('#section').selectOption('copy');await page.getByLabel('Título dos serviços').fill('Serviços personalizados');await save(page);
 const publicPage=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];publicPage.on('pageerror',error=>errors.push(error.message));try{
  await publicPage.goto('http://127.0.0.1:5173/');await expect(publicPage.locator('#site-header .brand-words')).toContainText('CLÍNICA TESTE');await expect(publicPage.locator('.header-cta')).toHaveText('Escolher meu horário');await expect(publicPage.locator('#header-account')).toHaveText('Acessar perfil');await expect(publicPage.locator('#navigation a').first()).toHaveText('Sobre');await expect(publicPage.locator('#navigation a').filter({hasText:'Instagram oficial'})).toHaveAttribute('rel','noopener noreferrer');await expect(publicPage.locator('#procedures-title')).toHaveText('Serviços personalizados');
  const footer=publicPage.locator('.premium-footer');await expect(footer).toContainText('MARCA DO RODAPÉ');await expect(footer).toContainText('Rua de Demonstração, 123');await expect(footer.locator('a[href="tel:+5511999990000"]')).toHaveText('+55 11 99999-0000');await expect(footer.locator('nav a').first()).toHaveText('Nossos serviços');await expect(footer.locator('#footer-contact a').first()).toHaveText('Enviar e-mail');await expect(footer.locator('#footer-demo')).toBeHidden();await expect(footer.locator('.footer-extra')).toHaveText('<img src=x onerror=alert(1)> texto simples');await expect(footer.locator('.footer-extra img')).toHaveCount(0);await footer.screenshot({path:test.info().outputPath('rodape-computador.png')});await footer.getByRole('button',{name:'Nossa privacidade'}).click();await expect(publicPage.locator('#info-body')).toHaveText('Política publicada pela clínica: conteúdo de teste.');await publicPage.getByRole('button',{name:'Fechar janela',exact:true}).click();
  await publicPage.locator('.header-cta').click();await expect(publicPage.locator('.customer-auth')).toBeVisible();await publicPage.goto('http://127.0.0.1:5173/');await publicPage.setViewportSize({width:390,height:844});await publicPage.getByRole('button',{name:'Abrir navegação'}).click();await expect(publicPage.getByRole('button',{name:'Fechar navegação'})).toHaveAttribute('aria-expanded','true');await publicPage.locator('#navigation a[href="#sobre"]').first().click();await expect(publicPage.getByRole('button',{name:'Abrir navegação'})).toHaveAttribute('aria-expanded','false');await footer.scrollIntoViewIfNeeded();await footer.screenshot({path:test.info().outputPath('rodape-celular.png')});expect(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
 }finally{await publicPage.close();}
 // A malicious destination is rejected in the editor without overwriting published links.
 await page.locator('#section').selectOption('header_links');await page.getByLabel('Destino do link',{exact:true}).first().fill('javascript:alert(1)');await page.getByRole('button',{name:'Salvar e publicar seção'}).click();await expect(page.locator('form [role=alert]')).toContainText('Destino inválido');
});
test('Custom logos, logged-in account labels and hidden header/footer controls are respected',async({page,browser})=>{
 let uid,cid;const password=randomBytes(20).toString('hex'),email=`chrome-customer-${Date.now()}@example.invalid`;
 const publicPage=await browser.newPage();try{
  uid=(await ok(service.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:'Cliente de Teste',phone:'11977776666',customer_consent:true}}))).user.id;cid=(await ok(service.from('customer_accounts').select('client_id').eq('user_id',uid).single())).client_id;
  await login(page);await page.locator('#section').selectOption('header');await page.locator('[name="0_logo"]').fill('/assets/hero.png');await page.getByLabel('Exibir botão de agendamento').selectOption('false');await page.getByLabel('Texto do perfil após entrar').fill('Meu espaço');await page.getByLabel('Exibir primeiro nome no perfil').selectOption('false');await save(page);
  await publicPage.goto('http://127.0.0.1:5173/');await expect(publicPage.locator('#site-header .brand-logo')).toHaveAttribute('src','/assets/hero.png');await expect(publicPage.locator('#site-header .header-cta,#site-header .nav-mobile-cta')).toHaveCount(0);await publicPage.locator('#header-account').click();await publicPage.getByLabel('E-mail',{exact:false}).fill(email);await publicPage.getByLabel('Senha',{exact:false}).fill(password);await publicPage.getByRole('button',{name:'Entrar',exact:true}).click();await expect(publicPage.getByRole('heading',{name:'Olá, Cliente.'})).toBeVisible();await publicPage.goto('http://127.0.0.1:5173/');await expect(publicPage.locator('#header-account')).toHaveText('Meu espaço');
  await page.getByLabel('Exibir acesso à conta').selectOption('false');await save(page);await page.locator('#section').selectOption('footer');await page.getByLabel('Exibir marca no rodapé').selectOption('false');await page.getByLabel('Exibir direitos autorais').selectOption('false');await page.getByLabel('Exibir botão de privacidade').selectOption('false');await page.getByLabel('Exibir botão de termos').selectOption('false');await save(page);
  await publicPage.reload();await expect(publicPage.locator('#site-header .brand-logo')).toBeVisible();await expect(publicPage.locator('#header-account')).toHaveCount(0);await expect(publicPage.locator('.premium-footer .brand,.premium-footer [data-legal]')).toHaveCount(0);await expect(publicPage.locator('#copyright')).toBeHidden();
 }finally{await publicPage.close();if(uid){if(cid){await service.from('customer_accounts').delete().eq('user_id',uid);await service.from('clients').delete().eq('id',cid);}await service.auth.admin.deleteUser(uid);}}
});
