import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createBookingHandler} from '../src/shared/booking-server.js';
const origin='https://clinic.example';const valid={procedure:randomUUID(),professional:randomUUID(),starts_at:'2026-10-20T12:00:00-03:00',consent:true,website:'',token:'valid-token',request_key:randomUUID()};
async function call({body=valid,headers={},method='POST',budget=true,captcha={},user={id:randomUUID(),email_confirmed_at:'2026-01-01'},config={},saveError=null}={}){
 const calls=[];const handler=createBookingHandler({getConfig:()=>({url:'https://example.supabase.co',secret:'server-only-test-secret',captchaSecret:'captcha-secret',origin,...config}),createService:()=>({rpc:async(name,args)=>{calls.push({name,args});return name==='consume_booking_budget'?{data:budget,error:null}:{data:randomUUID(),error:saveError};},auth:{getUser:async()=>({data:{user},error:null})}}),verifyCaptcha:async()=>({success:true,hostname:'clinic.example',action:'booking',...captcha})});
 const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(s){this.statusCode=s;return this;},json(b){this.body=b;return this;}};
 await handler({method,headers:{origin,'content-type':'application/json','x-vercel-forwarded-for':'203.0.113.9',authorization:'Bearer verified-session',...headers},body},res);return {...res,calls};
}
test('Booking requires configured server secrets and rejects foreign origin',async()=>{assert.equal((await call({config:{secret:''}})).statusCode,503);const r=await call({headers:{origin:'https://evil.example'}});assert.equal(r.statusCode,403);assert.equal(r.calls.length,0);});
test('Booking rejects non-POST, wrong content type and untrusted connection',async()=>{assert.equal((await call({method:'GET'})).statusCode,405);assert.equal((await call({headers:{'content-type':'text/plain'}})).statusCode,415);assert.equal((await call({headers:{'x-vercel-forwarded-for':''}})).statusCode,400);});
test('Booking validates strict fields, consent, oversized body and honeypot',async()=>{for(const body of [{...valid,consent:false},{...valid,procedure:'invalid'},{...valid,customer:randomUUID()},{...valid,website:'spam'}]){const r=await call({body});assert.equal(r.statusCode,400);assert.ok(!r.calls.some(c=>c.name==='submit_booking_request'));}assert.equal((await call({body:'x'.repeat(8193)})).statusCode,413);});
test('Booking verifies captcha success, hostname and action',async()=>{for(const captcha of [{success:false},{hostname:'evil.example'},{action:'auth'}]){const r=await call({captcha});assert.equal(r.statusCode,403);assert.ok(!r.calls.some(c=>c.name==='submit_booking_request'));}});
test('Rate limit happens before writes and hashes IP addresses',async()=>{const r=await call({budget:false});assert.equal(r.statusCode,429);assert.equal(r.calls.length,1);assert.match(r.calls[0].args.key_hash,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(r.calls).includes('203.0.113.9'));assert.equal(r.headers['Retry-After'],'3600');});
test('Anonymous and unconfirmed customers cannot book',async()=>{for(const options of [{headers:{authorization:''}},{user:null},{user:{id:randomUUID(),email_confirmed_at:null}}]){const r=await call(options);assert.equal(r.statusCode,401);assert.ok(!r.calls.some(c=>c.name==='submit_booking_request'));}});
test('Verified customer ID is derived from session and internal errors stay private',async()=>{const id=randomUUID();const r=await call({user:{id,email_confirmed_at:'2026-01-01'}});assert.equal(r.statusCode,200);assert.equal(r.calls.at(-1).args.customer,id);assert.deepEqual(r.body,{ok:true});const failed=await call({saveError:{message:'private SQL detail'}});assert.equal(failed.statusCode,503);assert.ok(!JSON.stringify(failed.body).includes('private SQL'));});
test('Duplicate customer requests and lost slots return actionable errors',async()=>{assert.equal((await call({saveError:{message:'Você já enviou um pedido.'}})).statusCode,429);assert.equal((await call({saveError:{message:'Horário indisponível.'}})).statusCode,409);assert.equal((await call({saveError:{message:'Cadastro de cliente necessário.'}})).statusCode,403);});
