import {db} from './supabase.js';
import {esc,date,time,labels} from './admin/ui.js';

const paths={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',calendar:'M5 5h14v16H5z M8 3v4 M16 3v4 M5 10h14',photos:'M4 4h16v16H4z M4 16l5-5 4 4 3-3 4 4 M15 8h.01',user:'M20 21v-2a7 7 0 0 0-14 0v2 M13 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8',arrow:'M5 12h14 M13 6l6 6-6 6',plus:'M12 5v14 M5 12h14',refresh:'M20 7v5h-5 M4 17v-5h5 M6 7a7 7 0 0 1 12-1l2 6 M4 12l2 6a7 7 0 0 0 12-1',lock:'M5 10h14v11H5z M8 10V7a4 4 0 0 1 8 0v3',exit:'M9 3H4v18h5 M10 12h11 M17 8l4 4-4 4',check:'M5 12l4 4L19 6'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name].split(' M').map((p,i)=>`<path d="${i?'M':''}${p}"/>`).join('')}</svg>`;
const tabs=[['visao-geral','Visão geral','overview'],['agendamentos','Agendamentos','calendar'],['acompanhamento','Acompanhamento','photos'],['meus-dados','Meus dados','user']];
const initialTab=()=>tabs.some(t=>t[0]===location.hash.slice(1))?location.hash.slice(1):'visao-geral';
const phone=value=>String(value||'').replace(/^(55)?(\d{2})(\d{4,5})(\d{4})$/,(_,country,ddd,first,last)=>`${country?'+55 ':''}(${ddd}) ${first}-${last}`);
const initials=name=>name.trim().split(/\s+/).filter(Boolean).slice(0,2).map(n=>n[0]).join('').toUpperCase();
const active=a=>a.status==='pending'||(['scheduled','confirmed','in_progress','approved'].includes(a.status)&&new Date(a.starts_at)>=new Date());
const status=a=>`<span class="account-status ${esc(a.status)}"><i></i>${esc(a.status==='pending'?'Aguardando aprovação':labels[a.status]||a.status)}</span>`;
function appointmentCard(a){
 const dt=new Date(a.starts_at);const day=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',timeZone:'America/Sao_Paulo'}).format(dt),month=new Intl.DateTimeFormat('pt-BR',{month:'short',timeZone:'America/Sao_Paulo'}).format(dt).replace('.','');
 return `<article class="appointment-card"><div class="appointment-date"><strong>${day}</strong><span>${esc(month)}</span></div><div class="appointment-copy"><h3>${esc(a.procedure_name)}</h3><p>${esc(a.professional_name)}<span aria-hidden="true"> · </span>${time(a.starts_at)}</p><small>${date(a.starts_at)} · Horário de Brasília</small></div>${status(a)}</article>`;
}
function empty(title,copy,type='calendar'){return `<div class="account-empty"><span class="empty-symbol">${icon(type)}</span><h3>${title}</h3><p>${copy}</p></div>`;}

export function mountCustomerProfile(root,{profile,session,onRefresh,onLogout}){
 let tab=initialTab(),filter='upcoming',disposed=false,photoVersion=0;const blobUrls=[];
 const client=profile.client,requests=profile.requests||[],appointments=profile.appointments||[],photos=profile.photos||[];
 // Approved requests become appointments; the appointment remains the source
 // of truth even if the clinic later reschedules or cancels it.
 const entries=[...appointments,...requests.filter(r=>r.status!=='approved')];
 const upcoming=entries.filter(active).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));const pending=requests.filter(r=>r.status==='pending');
 const clearPhotos=()=>{photoVersion++;blobUrls.forEach(URL.revokeObjectURL);blobUrls.length=0;root.querySelector('dialog')?.remove();};
 root.innerHTML=`<div class="account-page"><header class="account-heading"><div class="account-welcome"><span class="account-avatar">${esc(initials(client.name))}</span><div><p class="account-kicker">MEU PERFIL</p><h1>Olá, ${esc(client.name.split(' ')[0])}.</h1><p>Seu cuidado, organizado em um só lugar.</p></div></div><a class="account-primary" href="/cliente/agendar">${icon('plus')}Agendar avaliação</a></header><nav class="account-tabs" role="tablist" aria-label="Meu perfil">${tabs.map(([id,label,i])=>`<button type="button" role="tab" id="tab-${id}" aria-controls="panel-${id}" data-tab="${id}">${icon(i)}<span>${label}</span>${id==='agendamentos'&&pending.length?`<span class="tab-count">${pending.length}</span>`:''}</button>`).join('')}</nav><div id="account-content"></div><footer class="account-footer"><span>${icon('lock')} Seu espaço é privado. Só você e a equipe têm acesso.</span><div><button type="button" id="refresh">${icon('refresh')}Atualizar</button><button type="button" id="logout">${icon('exit')}Sair</button></div></footer></div>`;
 const content=root.querySelector('#account-content');
 const overview=()=>`<div class="account-stats"><button data-open="agendamentos"><span class="stat-icon">${icon('calendar')}</span><span><strong>${upcoming.filter(a=>a.status!=='pending').length}</strong><small>Próximas consultas</small></span>${icon('arrow')}</button><button data-open="agendamentos"><span class="stat-icon warm">${icon('refresh')}</span><span><strong>${pending.length}</strong><small>Pedidos em análise</small></span>${icon('arrow')}</button><button data-open="acompanhamento"><span class="stat-icon">${icon('photos')}</span><span><strong>${photos.length}</strong><small>Fotos do acompanhamento</small></span>${icon('arrow')}</button></div><div class="account-grid"><section class="account-card"><div class="account-card-heading"><div><h2>Seus próximos encontros</h2><p>Um momento reservado para você.</p></div><button class="account-text-button" data-open="agendamentos">Ver todos ${icon('arrow')}</button></div>${upcoming.length?`<div class="appointment-list">${upcoming.slice(0,3).map(appointmentCard).join('')}</div>`:empty('Seu próximo cuidado começa aqui.','Escolha um tratamento e solicite o melhor horário para você.')}<div class="account-card-foot">${icon('check')} A equipe confirma cada pedido antes do atendimento.</div></section><aside class="account-side-card"><p class="account-kicker">PASSO A PASSO</p><h2>Tempo para<br> cuidar de você.</h2><p>Escolha seu tratamento, envie um pedido e acompanhe a confirmação por aqui.</p><a href="/cliente/agendar" class="account-text-button">Encontrar um horário ${icon('arrow')}</a><div class="account-quota">${icon('calendar')}<p><strong>Até 2 consultas por semana</strong><span>De segunda a domingo. Pedidos pendentes também contam.</span></p></div></aside></div>`;
 const bookings=()=>{const list=entries.filter(a=>filter==='upcoming'?active(a):!active(a)).sort((a,b)=>filter==='upcoming'?new Date(a.starts_at)-new Date(b.starts_at):new Date(b.starts_at)-new Date(a.starts_at));return `<section class="account-card"><div class="account-card-heading"><div><h2>Meus agendamentos</h2><p>Pedidos, confirmações e histórico de atendimento.</p></div><div class="account-segment" aria-label="Filtrar agendamentos"><button data-filter="upcoming" aria-pressed="${filter==='upcoming'}">Próximos</button><button data-filter="history" aria-pressed="${filter==='history'}">Histórico</button></div></div>${list.length?`<div class="appointment-list">${list.map(appointmentCard).join('')}</div>`:empty(filter==='upcoming'?'Sua agenda está livre.':'Seu histórico começa no primeiro encontro.',filter==='upcoming'?'Quando você solicitar um horário, ele aparecerá aqui.':'Os atendimentos anteriores e pedidos encerrados ficam nesta aba.')}<div class="account-card-foot">${icon('calendar')} Horários de Brasília. Pedidos aguardam aprovação da clínica.</div></section>`;};
 const evolution=()=>`<section class="account-card"><div class="account-card-heading"><div><h2>Meu acompanhamento</h2><p>Seu progresso, registrado com cuidado pela equipe.</p></div><span class="account-private">${icon('lock')} Privado</span></div>${photos.length?`<div class="account-photos">${photos.map(p=>`<article class="account-photo"><button type="button" data-photo="${p.id}" disabled aria-label="Ampliar foto de ${esc(p.procedure_name)}"><span class="photo-loading">Carregando foto…</span><img data-private="${p.id}" alt="${esc(p.procedure_name)} — ${esc(labels[p.category]||p.category)}" hidden></button><div><span>${esc(labels[p.category]||p.category)}</span><h3>${esc(p.procedure_name)}</h3><p>${date(p.taken_on)}</p></div></article>`).join('')}</div>`:empty('Cada etapa merece ser acompanhada.','As fotos liberadas pela clínica aparecerão aqui, em uma galeria só sua.','photos')}</section>`;
 const details=()=>`<div class="account-grid"><section class="account-card"><div class="account-card-heading"><div><h2>Meus dados</h2><p>As informações vinculadas ao seu atendimento.</p></div>${icon('user')}</div><dl class="account-details"><div><dt>Nome completo</dt><dd>${esc(client.name)}</dd></div><div><dt>E-mail de acesso</dt><dd>${esc(session.user.email)}</dd></div><div><dt>WhatsApp</dt><dd>${esc(phone(client.whatsapp))}</dd></div></dl><div class="account-card-foot">Para atualizar seus dados, entre em contato com a clínica.</div></section><aside class="account-side-card"><span class="empty-symbol">${icon('lock')}</span><h2>Sua conta.<br> Seu espaço.</h2><p>Seus agendamentos e fotos de acompanhamento ficam disponíveis somente para você e a equipe responsável.</p><a class="account-text-button" href="/#contato">Contato da clínica ${icon('arrow')}</a></aside></div>`;
 async function loadPhotos(){const version=photoVersion;for(const p of photos){if(disposed||version!==photoVersion)return;const {data,error}=await db.storage.from('evolution').download(p.object_path);if(disposed||version!==photoVersion)return;const button=root.querySelector(`[data-photo="${p.id}"]`);if(error){button.querySelector('.photo-loading').textContent='Foto indisponível no momento.';continue;}const url=URL.createObjectURL(data);blobUrls.push(url);const img=button.querySelector('img');img.src=url;img.hidden=false;button.querySelector('.photo-loading').remove();button.disabled=false;button.onclick=()=>{const dialog=document.createElement('dialog');dialog.className='account-photo-dialog';dialog.innerHTML=`<button type="button" aria-label="Fechar foto">×</button><img src="${url}" alt="${esc(p.procedure_name)}"><p>${esc(p.procedure_name)} · ${date(p.taken_on)}</p>`;root.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();};}}
 function draw(focus=false){if(disposed)return;clearPhotos();root.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.tab===tab));b.tabIndex=b.dataset.tab===tab?0:-1;});content.innerHTML=`<section role="tabpanel" id="panel-${tab}" aria-labelledby="tab-${tab}" tabindex="0">${tab==='visao-geral'?overview():tab==='agendamentos'?bookings():tab==='acompanhamento'?evolution():details()}</section>`;root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>select(b.dataset.open,true));root.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;draw();root.querySelector(`[data-filter="${filter}"]`).focus();});if(tab==='acompanhamento')loadPhotos();if(focus)root.querySelector(`#tab-${tab}`).focus();}
 function select(id,focus=false){tab=id;history.replaceState({},'',location.pathname+location.search+'#'+id);draw(focus);}
 root.querySelectorAll('[data-tab]').forEach(b=>{b.onclick=()=>select(b.dataset.tab);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const i=tabs.findIndex(t=>t[0]===tab);select(tabs[e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length][0],true);};});
 root.querySelector('#refresh').onclick=async e=>{e.currentTarget.disabled=true;await onRefresh();};root.querySelector('#logout').onclick=onLogout;
 const onHash=()=>{tab=initialTab();draw();};window.addEventListener('hashchange',onHash);draw();
 return ()=>{disposed=true;clearPhotos();window.removeEventListener('hashchange',onHash);};
}
